//USER DEFINITIONS
#define DEBUG_PRINT 1

//DEVICE DEFINITIONS
#define PARTNUMBER "100007"
#define DEVICETYPE "GPIOHat"
#define DEVICENAME "GPIOHat1"
#define DEVICEID 20

#define DIAG_SYSTEM ROVER
#define DIAG_SUBSYSTEM ROBOT_CONTROLLER

//PIN DEFINITIONS
#define FLSONAR 8
#define FRSONAR 9
#define BLSONAR 10
#define BRSONAR 11


