//USER DEFINITIONS
#define DEBUG_PRINT 1

#define VERYVERYSLOWLOOP_RATE 30000 //mS
#define VERYSLOWLOOP_RATE 10000 //mS
#define SLOWLOOP_RATE 1000 //mS
#define MEDIUMLOOP_RATE 200 //mS
#define FASTLOOP_RATE 10 //mS

//DEVICE DEFINITIONS
#define PARTNUMBER "100007"
#define DEVICETYPE "GPIOHat"
#define DEVICENAME "GPIOHat1"
#define DEVICEID 20

//CHILD DEVICE DEFINITIONS
#define IMU1_ID 0
#define IMU2_ID 1

#define DIAG_SYSTEM ROVER
#define DIAG_SUBSYSTEM ROBOT_CONTROLLER

//PIN DEFINITIONS
#define FLSONAR 8  //CHECK PIN, LOOKS LIKE IT IS DISCONNECTED
#define FRSONAR 9
#define BLSONAR 10
#define BRSONAR 11

#define IMU1_SCLK 21
#define IMU1_MISO 19
#define IMU1_MOSI 20
#define IMU1_XM_CS 22
#define IMU1_GYRO_CS 23
#define IMU2_SCLK 4
#define IMU2_MISO 18
#define IMU2_MOSI 5
#define IMU2_XM_CS 7
#define IMU2_GYRO_CS 13
