//USER DEFINITIONS
#define DEBUG_PRINT 1

//DEVICE DEFINITIONS
#define PARTNUMBER "100005"
#define DEVICETYPE "ArduinoBoard"
#define DEVICENAME "ArduinoBoard1"
#define DEVICEID "0"

#define DIAG_SYSTEM ROVER
#define DIAG_SUBSYSTEM ROBOT_CONTROLLER

//PIN DEFINITIONS
#define LEDSTRIP_PIN 47
#define ENCODERLEFTA_PIN 18
#define ENCODERLEFTB_PIN 19
#define ENCODERRIGHTA_PIN 2
#define ENCODERRIGHTB_PIN 3

//LEDSTRIP DEFINITIONS
#define LEDSTRIP_PIXELCOUNT 32

//ENCODER DEFINITIONS
#define LEFTENCODER_SCALE 0.5
#define RIGHTENCODER_SCALE 0.5
